# This workflow will execute the accompanying btests

name: Zeek 2.3

# Controls when the action will run. Triggers the workflow on push or pull request
on:
  push:
  pull_request:
  schedule:
    - cron:  '0 8 15 * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test_centos_6:
    name: CentOS 6 with Zeek 2.3
    runs-on: ubuntu-20.04
    container:
      image: grigorescu/zeek_centos_6:2.3

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v1
      with:
        submodules: recursive

    - name: Test
      run: $GITHUB_WORKSPACE/.helpers/test.sh
