# This tests Zeek master + CentOS 7

name: Zeek master

# Controls when the action will run. Triggers the workflow on push or pull request
on:
  push:
  pull_request:
  schedule:
    - cron:  '0 8 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test_centos_7:
    name: CentOS 7 with Zeek master
    runs-on: ubuntu-20.04
    container:
      image: grigorescu/zeek_centos_7:latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v1
      with:
        submodules: recursive

    - name: Test
      run: $GITHUB_WORKSPACE/.helpers/test.sh
