# This workflow will run the package with Vern's script optimization branch,
# failing if any bugs or potential issues are detected. This will catch things
# like an optional record field being accessed without checking for existence of
# that field.

name: Script optimizer checks

# Controls when the action will run. Triggers the workflow on push or pull request
on:
  push:
  pull_request:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test_centos_7:
    name: CentOS 7 with script optimizer
    runs-on: ubuntu-20.04
    container:
      image: grigorescu/zeek_centos_7:script_optimizer

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v1
      with:
        submodules: recursive

    - name: Test
      run: $GITHUB_WORKSPACE/.helpers/test.sh

    - name: Run optimizer
      run: |
        /usr/local/zeek/bin/zeek -buu $GITHUB_WORKSPACE/scripts > output 2>&1
        [[ -s output ]] && ( cat output; exit 1) || true
