# This workflow will attempt to run the tests via zkg, and then install it.
# It tests CentOS 8, Ubuntu 18, and 20 (with CentOS 7 being tested by the other jobs)

name: Other Distros

# Controls when the action will run. Triggers the workflow on push or pull request
on:
  push:
  pull_request:
  schedule:
    - cron:  '30 8 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    name: Ubuntu ${{ matrix.distro_version }} with Zeek ${{ matrix.zeek }}
    runs-on: ubuntu-20.04
    container:
      image: grigorescu/zeek_ubuntu_${{ matrix.distro_version }}:${{ matrix.zeek }}

    strategy:
      fail-fast: false
      matrix:
        zeek: ["3.0", "3.1", "3.2", "preview", "latest"]
        distro_version: ["18", "20"]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: zkg autoconfig
      run: PATH=/usr/local/zeek/bin:$PATH zkg autoconfig

    - name: Test with zkg
      run: PATH=/usr/local/zeek/bin:$PATH zkg test https://github.com/${GITHUB_REPOSITORY}.git --version ${GITHUB_SHA} || ( cat /github/home/.zkg/testing/*.git/clones/*.git/zkg.test_command*; exit 1 )

    - name: Install with zkg
      run: PATH=/usr/local/zeek/bin:$PATH zkg install --skiptests --force https://github.com/${GITHUB_REPOSITORY}.git --version ${GITHUB_SHA}

  test_centos_8:
    name: CentOS 8 with Zeek ${{ matrix.zeek }}
    runs-on: ubuntu-20.04
    container:
      image: grigorescu/zeek_centos_8:${{ matrix.zeek }}

    strategy:
      fail-fast: false
      matrix:
        zeek: ["3.0", "3.1", "3.2", "preview", "latest"]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: zkg autoconfig
      run: PATH=/usr/local/zeek/bin:$PATH zkg autoconfig

    - name: Test with zkg
      run: PATH=/usr/local/zeek/bin:$PATH zkg test https://github.com/${GITHUB_REPOSITORY}.git --version ${GITHUB_SHA} || ( cat /github/home/.zkg/testing/*.git/clones/*.git/zkg.test_command*; exit 1 )

    - name: Install with zkg
      run: PATH=/usr/local/zeek/bin:$PATH zkg install --skiptests --force https://github.com/${GITHUB_REPOSITORY}.git --version ${GITHUB_SHA}
