#!/bin/bash

if [ -d .git ]; then
   echo "Looks like git is already initialized. Refusing to continue"
   exit 1
fi

git init
git add .
git commit -m "Initial commit [cookiecutter-zeekpackage]"

git checkout --orphan gh-pages
git reset --hard
git commit --allow-empty -m "Initializing gh-pages branch"
git checkout master
