variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - test

test:
  image: grigorescu/zeek_ubuntu_20:3.2
  stage: test
  before_script:
    - ./.helpers/install_pips.sh
    - ./.helpers/install_zkg.sh
  script:
    - ./.helpers/test.sh
  artifacts:
    reports:
      cobertura: .coverage.cobertura.xml
      junit: .btest_output.xml
