# Config file for automatic testing at travis-ci.com

language: cpp
dist: bionic

addons:
  apt:
    sources:
      - sourceline: 'deb http://download.opensuse.org/repositories/security:/zeek/xUbuntu_18.04/ /'
        key_url: 'https://download.opensuse.org/repositories/security:zeek/xUbuntu_18.04/Release.key'
    packages:
    - zeek-core

before_script:
  - pip install --user cpp-coveralls

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: sudo bash ./.ci_scripts/install.sh

# Command to run tests, e.g. python setup.py test
script: sudo bash ./.ci_scripts/test.sh

after_success:
  - coveralls -i scripts --gcov-options '\-lp'
