# Config file for automatic testing at travis-ci.com

language: minimal
dist: bionic

matrix:
  include:
    - name: Zeek LTS
      addons:
        apt:
          sources:
            - sourceline: 'deb http://download.opensuse.org/repositories/security:/zeek/xUbuntu_18.04/ /'
              key_url: 'https://download.opensuse.org/repositories/security:zeek/xUbuntu_18.04/Release.key'
          packages:
            - zeek-lts-core

    - name: Zeek Current
      addons:
        apt:
          sources:
            - sourceline: 'deb http://download.opensuse.org/repositories/security:/zeek/xUbuntu_18.04/ /'
              key_url: 'https://download.opensuse.org/repositories/security:zeek/xUbuntu_18.04/Release.key'
          packages:
            - zeek-core

    - name: Zeek Nightly
      addons:
        apt:
          sources:
            - sourceline: 'deb http://download.opensuse.org/repositories/security:/zeek/xUbuntu_18.04/ /'
              key_url: 'https://download.opensuse.org/repositories/security:zeek/xUbuntu_18.04/Release.key'
          packages:
            - zeek-nightly-core

before_script:
  - sudo pip install cpp-coveralls

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: sudo bash ./.ci_scripts/install.sh

# Command to run tests, e.g. python setup.py test
script: sudo bash ./.ci_scripts/test.sh

# Push documentation to GitHub
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  on:
    branch: master
  local_dir: _build/html/
